### ISSUE TITLE
doesn't work on arch linux

### ISSUE THREAD

**Issue by 20NE** [seclab-ucr/INTANG#1]
platform:
arch linux (4.12.8-2-ARCH)

the output of run.sh:

693:C 03 Nov 12:09:11.340 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
693:C 03 Nov 12:09:11.341 # Redis version=4.0.2, bits=32, commit=00000000, modified=0, pid=693, just started
693:C 03 Nov 12:09:11.341 # Configuration loaded
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.

log:
1509682151.259493 [INFO] Current version: 7
1509682151.259821 [INFO] Starting redis server.
1509682151.401993 [INFO] Saving TTL to redis
1509682151.610254 [INFO] Killing redis server (pid 694).
1509682151.610434 [INFO] Daemon exited.

**Comment by 4ft35t** [comment]
Ubuntu 16.04.2 LTS
4.12.2-041202-generic #201707150832 SMP Sat Jul 15 12:34:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

same issue.

**Comment by 20NE** [comment]
now

output:
1103:C 03 Nov 15:43:49.538 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1103:C 03 Nov 15:43:49.538 # Redis version=4.0.2, bits=32, commit=00000000, modified=0, pid=1103, just started
1103:C 03 Nov 15:43:49.538 # Configuration loaded

log:
1509693146.155325 [INFO] Current version: 7
1509693146.155694 [INFO] Starting redis server.
1509693146.172609 [ERROR] error during nfq_create_queue()
1509693146.172683 [ERROR] unable to setup netfilter_queue

**Comment by gkso** [comment]
Have successfully installed all the prerequisites in install.sh? And running the tool with root privilege?

**Comment by 20NE** [comment]
I've installed all the prerequisites but python-scapy (optional).
make it sucessfully.
sure I run it with root privilege.

**Comment by gkso** [comment]
Thanks for the feedback. Looks like some bug caused the tool exit unexpectedly. In between "1509682151.401993 [INFO] Saving TTL to redis
1509682151.610254 [INFO] Killing redis server (pid 694)."
I will try to look into that shortly.

**Comment by gkso** [comment]
Bug fixed at 85a644d9f68fe202c7dd61be94ef792fc6a66629
Bug was introduced by some recent commit.

**Comment by V-E-O** [comment]
Still crashes on Kali/Debian with root and deps installed.

1509812530.531059 [INFO] [EVAL] STRATEGY FAILED 1. HTTP NO RESPONSE. 1828825280_4760_3340334402_20480_12
1509812533.029715 [INFO] [EVAL] STRATEGY SUCCEEDED. 1828825280_58538_3271849064_20480_6
1509812533.611976 [INFO] [EVAL] STRATEGY FAILED 1. HTTP NO RESPONSE. 1828825280_58026_3271849064_20480_6
1509812533.737840 [INFO] Saving TTL to redis
1509812533.903064 [ERROR] error during nfq_destroy_queue()
1509812533.903167 [INFO] Killing redis server (pid 1627).
1509812533.903217 [INFO] Daemon exited.
